### ISSUE TITLE
unexpected 403 error while downloading m3u8 playlist 

### ISSUE THREAD

**Issue by tcamnsk001** [prof79/fansly-downloader-ng#23]
## Bug Description
downloader encounters response code 403 access denied while downloading m3u8 playlist info after this a runtime Error occurs in mp4.py at line 122 where it attempts to convert the m3u8 video that did not download to mp4. after this the downloader does not continue and attempts to download the video again only to encounter the same response code it then finishes without collecting any further media.

## Expected behavior
to download the video and convert it to mp4

## Actual behavior
the downloader recieves a 403 access denied message and does not download any further media

*( If applicable, [add screenshots](https://stackoverflow.com/a/14494775/15163882) to help explain your problem. )*
![githubbug](https://github.com/prof79/fansly-downloader-ng/assets/160380972/b76324ff-f5fd-44a4-9655-30a2a9f61119)

## Environment Information
 - Operating System: windows 10
 - Fansly Downloader Version: V 0.8.16
 - Fansly Downloader Type: Windows executable
 - Specific creators name: rxvengrxves

## User Research

I have done the following:
- [ x] Looked through [old GitHub issues]
- [ x] Read the [config.ini options]
- [ x] Searched on [Google]

**Comment by lordoffools** [comment]
Anyone having any luck with this?

**Comment by OzMantis** [comment]
No. I get this error:

[ Info ] [2024-02-19 | 19:49]: Downloading video '2024-01-23_at_01-35_id_605831545218932736.m3u8'
[ WARNING ] [2024-02-19 | 19:49]: Fansly returned an empty M3U8 playlist. I'll try fetch a 1080p version, this might fail!
[ [12]ERROR ] [2024-02-19 | 19:49]: Failed downloading M3U8 playlist info. Response code: 403
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>[redacted]</RequestId><HostId>[redacted]</HostId></Error>
[ WARNING ] [2024-02-19 | 19:49]: Skipping invalid item: Failed downloading M3U8 playlist info. Response code: 403

**Comment by prof79** [comment]
As you might have noticed we had a lengthy resolution process due to naming changes of Fansly for vids published in Feb '24 onwards under https://github.com/prof79/fansly-downloader-ng/issues/17 and all people went happily thereafter.

I just did a full scrape of one of my paid creators and downloaded 169 vids in 16 GiB without a hitch back to Aug 2022 and up to Feb 23 2024.

Therefore, with the information provided, there is nothing I can do unless I had a creator name where, without having to pay/follow-only, I could reproduce the issue and diagnose the Fansly data responses and their effects in the downloader code.

I'm still waiting for @tcamnsk001 feedback. You @lordoffools  and and @left1000  did not describe whether you get the original message or what @OzMantis posted/tried v0.8.17.

@OzMantis posted the only meaningful feedback where I can say this is a side-effect of fixing #17 for some old videos (before Februrary) where Fansly provides a wrong (empty) playlist response. I could try to "guess better" attempting a kind-of fallback/old logic inspired path/parallel path when an empty playlist surfaces which is somewhat complicated to implement.

**Comment by left1000** [comment]
Nevermind my question, my rip was flawless today.

**Comment by lordoffools** [comment]
Thanks for the nudge, and for your patience with my update here, @prof79. I can confirm after a few hours of downloading and a couple different paid creators, that I can no longe reproduce this issue.

**Comment by prof79** [comment]
Thanks @left1000 @lordoffools I'll keep it open for tracking since what @OzMantis confirmed - though a rare Fansly error with root playlists - the resolution strategy could be approved upon.

**Comment by tcamnsk001** [comment]
sorry for the long wait. this resolved most of my issues i am still unable to download certain .m3u8 videos but it skipped over them and downloaded other content without issues

**Comment by tcamnsk001** [comment]
sorry for the long wait. this resolved most of my issues i am still unable to download certain .m3u8 videos but it skipped over them and downloaded other content without issues

**Comment by lipefleming** [comment]
How do I solve this? I'm using the latest version, and I can't download a single file of a specific profile.
