### ISSUE TITLE
remoted end closed without response

### ISSUE THREAD

**Issue by mrtuxa** [prof79/fansly-downloader-ng#28]
## Expected behavior
Traceback (most recent call last):
  File "download/timeline.py", line 46, in download_timeline
  File "config/fanslyconfig.py", line 253, in cors_options_request
  File "requests/sessions.py", line 613, in options
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 501, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

## Environment Information
 - Operating System: Debian 11
 - Fansly Downloader Version: 
 - Fansly Downloader Type: Executable
 - Specific creators name: hunnypaint

## User Research

I have done the following:
- [x] Looked through [old GitHub issues](https://github.com/Avnsx/fansly-downloader/issues?&q=is%3Aissue)
- [x] Read the [config.ini options](https://github.com/Avnsx/fansly-downloader/wiki/Explanation-of-provided-programs-&-their-functionality#explanation-of-configini)
- [x] Searched on [Google](https://www.google.com/search?q=how+do+I+foo)

**Comment by prof79** [comment]
Need to make some tests but that may get difficult - this is a generic HTTP call error and usually points to a network-related issue. Could also be a server issue but very unlikely since Fansly certainly has high availability and resolution strategies/takeover when a server fails.

Are you performing this at home with an unrestricted internet access? There are three things that could also cause this and they inter-relate:

1. Proxy server required (usually campus/corpo environments)
2. Firewall/network security
3. Endpoint security software

Does this always happen regardless the creator?

**Comment by prof79** [comment]
No response.
