### ISSUE TITLE
Dowloading never starts

### ISSUE THREAD

**Issue by secondbabe** [prof79/fansly-downloader-ng#30]
Program gets through the config check, name validation, local directory acknowledge, notification of hash format rename, and deduplication information, then stops. No files get downloaded or even looked at.

**Comment by prof79** [comment]
Could you provide more info like requested in the issue template - like operating system, FDNG version and a screenshot and/or contents of the program's log file could be helpful.

**Comment by secondbabe** [comment]
> Could you provide more info like requested in the issue template - like operating system, FDNG version and a screenshot and/or contents of the program's log file could be helpful.

Windows 10, ver 0.8.17 and strangely enough the program does work properly when downloading from a new creator, just not one that has previously had files downloaded from. 
![ApplicationFrameHost_dL6yCQMfd7](https://github.com/prof79/fansly-downloader-ng/assets/162537945/a1c3e10c-874d-4e37-a4f6-64b294d8235c)

**Comment by prof79** [comment]
This is very odd! So the downloader just hangs and you have to `CTRL+C` out of it/use Task Manager to kill? 

From the screen it looks like stuck or rather trying to do something in the file system where it never finishes; does the drive LED blink/do you have disk activity when this happens? Could there be something like a security solution blocking something?

I mean this extremely puzzling - because if there were no permissions or an anti-malware software preventing writes or any other error with file paths and special characters or whatever thinkable - than the program should crash with an exception. Is `F:` a partition of a disk within the computer or is this some kind of external drive?

This is just a shot in the dark but you might try one of the newer versions from today like v0.8.19. Maybe this has something to do with the `pyinstaller` packaging - you're using the binary download I assume?

It would be cool if you could run the source code version using a locally installed Python interpreter to rule out something with `pyinstaller` but I don't know how technically skilled you are.

**Comment by prof79** [comment]
Btw `Deduplication is automatically ...` is immediately shown before `add_hash_to_folder_items()` ie. what this does is recursively skimming all folders and files of the creator and adding hashes to file where appropriate in a multi-threaded way.

This adds to my suspicions that you might have some I/O performance issues with that drive. How long did you try letting it run?
I'd suggest maybe let it run 1-2h without letting the PC go to sleep and see what happens.
Trying another drive for creator downloads to narrow the problem is another option.
Finally you could also try downloading with deduplication disabled.

**Comment by secondbabe** [comment]
> This is very odd! So the downloader just hangs and you have to `CTRL+C` out of it/use Task Manager to kill?
>

No task manager needed, the program still exits as easily as standard. It just freezes on that screen. 
 
> From the screen it looks like stuck or rather trying to do something in the file system where it never finishes; does the drive LED blink/do you have disk activity when this happens? Could there be something like a security solution blocking something?
> 

It does show activity, but since I have other things running on the drive it might not be the program itself. Definitely not a security issue, especially since the downloader still works for creators that I hadn't downloaded things from before. 

> I mean this extremely puzzling - because if there were no permissions or an anti-malware software preventing writes or any other error with file paths and special characters or whatever thinkable - than the program should crash with an exception. Is `F:` a partition of a disk within the computer or is this some kind of external drive?
> 

It's an external drive, not a partition, but there's no anti-malware or anything that I'm aware of that would interfere. 

> This is just a shot in the dark but you might try one of the newer versions from today like v0.8.19. Maybe this has something to do with the `pyinstaller` packaging - you're using the binary download I assume?
> 

I'll try the newest version out, and let you know if it works!

> It would be cool if you could run the source code version using a locally installed Python interpreter to rule out something with `pyinstaller` but I don't know how technically skilled you are.

I am, unfortunately, pretty technically stupid.

**Comment by secondbabe** [comment]
> Btw `Deduplication is automatically ...` is immediately shown before `add_hash_to_folder_items()` ie. what this does is recursively skimming all folders and files of the creator and adding hashes to file where appropriate in a multi-threaded way.
> 
> This adds to my suspicions that you might have some I/O performance issues with that drive. How long did you try letting it run? I'd suggest maybe let it run 1-2h without letting the PC go to sleep and see what happens. Trying another drive for creator downloads to narrow the problem is another option. Finally you could also try downloading with deduplication disabled.

Seems like that was the issue! I used v0.8.19 and let it sit for several hours, ended up working eventually.

**Comment by prof79** [comment]
Great! An USB drive can be especially slow depending on whether it is already USB 3.x (as well as the computer ports you plug into) and also the issue of traditional spinning disks vs. SSDs.

But currently and sadly there are other problems at hand as Fansly have beefed up their security game currently breaking the downloader as a whole -.-

**Comment by prof79** [comment]
Progress bar would be feature request #33 but due to the current state of affairs will never do

**Comment by kwinz** [comment]
I have the same problem. Instead of resuming download with deduplication it hangs at:

``` [ Info ] [2024-03-30 | 11:32]: Deduplication is automatically enabled for: ```

No disk access,
no network access,
process using around 8% CPU (=1 core of 12)
I let it run for 10 hours, no progress or any more log output.

**Comment by kwinz** [comment]
Update: I had a single file that didn't have `_hash2_` in its name. Out of curiousity I deleted it and restarted. Now it works!
It skipped all already present media files and resumed downloading.
